### ISSUE TITLE
Document elsewhere talking about Schnorr under secp256k1

### ISSUE THREAD

**Issue by ChristopherA** [ElementsProject/secp256k1-zkp#1]
We have posted an advance reading for a designshop on the topic of "Rebooting the Web of Trust" which talks about moving over to Schnorr signatures, and specifically refers to this library. Can someone involved in this library read over and post issues there about any inaccuracies, or other comments about using Schnorr signatures under secp256k1? Thanks!

https://github.com/WebOfTrustInfo/rebooting-the-web-of-trust/blob/master/topics-and-advance-readings/Schnorr-Signatures--An-Overview.md

-- Christopher Allen

**Comment by sipa** [comment]
secp256k1-zkp is a fork of libsecp256k1 (https://github.com/bitcoin/secp256k1). I think that only the Borromean signatures are a relevant feature for you. For the rest, the original library (which I'm the primary author of as well) probably should be the focus.

**Comment by apoelstra** [comment]
Closing as our messaging around "Schnorr signatures" has changed to focus on Taproot (and has changed from being a -zkp project to being a Bitcoin-wide thing that hopefully will land upstream soon).
