### ISSUE TITLE
Rename default branch from `secp256k1-zkp` to `master`

### ISSUE THREAD

**Issue by jonasnick** [ElementsProject/secp256k1-zkp#121]
IIRC that's a remnant of the time when secp256k1-zkp was rebased on upstream. But I think it's confusing now.

**Comment by apoelstra** [comment]
+1

**Comment by jonasnick** [comment]
Done. Deleted `secp256k1-zkp` to make clear that this isn't going to be updated.

**Comment by real-or-random** [comment]
We need to update travis: https://travis-ci.org/github/ElementsProject/secp256k1-zkp/jobs/754182998#L214
(Well, we anyway need to switch away but let's update it as long as it's still up.)

**Comment by real-or-random** [comment]
> We need to update travis: https://travis-ci.org/github/ElementsProject/secp256k1-zkp/jobs/754182998#L214
> (Well, we anyway need to switch away but let's update it as long as it's still up.)

Ah no, it just works: https://travis-ci.org/github/ElementsProject/secp256k1-zkp/builds/754177884 The hiccup was just due to the branch being deleted during the travis run...
