### ISSUE TITLE
musig module

### ISSUE THREAD

**Issue by eyebrown** [ElementsProject/secp256k1-zkp#133]
I want  to use musig api in my program. I run the following commands:
    ./autogen.sh
    ./configure --enable-experimental --enable-module-schnorrsig --enable-module-musig
    make 
    sudo make install
Then,the headfiles are in /usr/local/include directory,libsecp256k1.a is in /usr/local/lib directory.
I include the main_impl.h in my program,but I meet the problem of "invalid use of incomplete typedef ‘secp256k1_context'","unknown type name ‘secp256k1_scalar’"and so on .What else should I do?

**Comment by jonasnick** [comment]
Hi @eyebrown. You should not include `main_impl.h` but instead the header files in `include/`.
