### ISSUE TITLE
Context initializers

### ISSUE THREAD

**Issue by osaka-kun** [ElementsProject/secp256k1-zkp#15]
I found that functions `secp256k1_pedersen_context_initialize` and `secp256k1_rangeproof_context_initialize` declared in `/include/secp256k1_rangeproof.h` have no implementations. 
Is it true, that it is unnecessary to additionaly initialize context?

**Comment by apoelstra** [comment]
Yes, it is true. The additional initilaization was removed when we implemented Assets.

I had thought we'd removed the declarations from `/include/secp256k1_rangeproof.h` but apparently not. I'll leave this bug open until we fix that.
