### ISSUE TITLE
Can one prove that a particular public key is part of an aggregated (MuSig) public key?

### ISSUE THREAD

**Issue by vitruvvius** [ElementsProject/secp256k1-zkp#206]
We generate a group signature, built w/ N individual secret/public keys.
We then sign a transaction using the group signature.
We then send a message, including the group key & signature in a payload.

We're now at the receiver of this message.
We have the group key, the group signature.
**We also have 1 / N of those original, individual public keys.**
How can we prove that 1 key is part of the group key?
How can we prove that 1 key is part of the group signature?
If not, why not?

Thanks for a lovely library :)

**Comment by apoelstra** [comment]
I think, everyone subscribed here is subscribed to https://github.com/bitcoin-core/secp256k1/issues/1162 where it looks like you've got a reply, so I'll close this one.
