### ISSUE TITLE
secp256k1-zkp with CMakeLists?

### ISSUE THREAD

**Issue by mattiaferrari02** [ElementsProject/secp256k1-zkp#209]
Is there a way to use this code in java?

**Comment by delta1** [comment]
Presumably you could use [JNI](https://www.baeldung.com/jni) to call the dynamically loaded library

**Comment by t-bast** [comment]
You can have a look at https://github.com/ACINQ/secp256k1-kmp/ where we do this for secp256k1 (but not the zkp version).

**Comment by real-or-random** [comment]
There's work for initial work for CMake for secp256k1 (not zkp) here: https://github.com/bitcoin-core/secp256k1/pull/1113 Maybe this helps but you'll be on your own.
