### ISSUE TITLE
undefined reference to `secp256k1_generator_h'

### ISSUE THREAD

**Issue by FrankC01** [ElementsProject/secp256k1-zkp#26]
Just trying to get up and running, the following:

```
// Preamble omited

secp256k1_pedersen_commit(none, &commit, blind, val, secp256k1_generator_h);
```
compiles OK but I get the undefined reference error noted in subject when linking.

Setting it to NULL compiles and links OK.

Is that generator not meant to be used?

**Comment by apoelstra** [comment]
You need to compile with `--enable-module-rangeproof` to get this symbol.

In future it will be moved to the generator module where it belongs and be renamed to `secp256k1_generator_const_h`. This is part of #23 .

**Comment by FrankC01** [comment]
I should have mentioned that in the original post but when I build the library here is my flags in the ./configure step:

`./configure --enable-module-generator --enable-experimental --enable-module-ecdh --enable-module-rangeproof`
