### ISSUE TITLE
General interface for curve points

### ISSUE THREAD

**Issue by WTRMQDev** [ElementsProject/secp256k1-zkp#32]
Libsecp256k1 provides an interface for operations on curve secp256k1. However, following the principle "Be difficult to use insecurely", only a specific API which directly describes operands was exposed. For instance, instead of functions for sum and multiply by scalars on curve points, only specific functions for sum and multiplications for public keys were made available.

However, during development the number of objects which inherently are points on curve has been growing and presently there are public keys, pedersen commitments and generators.

Our application (leer) requires (de)serialization for curve points independent of the nature of those points (we are developing a virtual machine where stack may contain curve points and has native opcodes for curve operations). Besides that, such functionality is required by libsecp256k1 modules by themselves: rangeproof module uses its own point serialization format https://github.com/ElementsProject/secp256k1-zkp/blob/secp256k1-zkp/src/modules/rangeproof/rangeproof_impl.h#L54 .

Hence it looks expedient to provide API for point (de)serialization as well as for bidirectional casting between points and other objects with specific purposes (that are inherently points) .

### Chosing of header byte
Currently there are these rules for headers byte.
Header bytes `0b00000000`,`0b00000001`,`0b00000110` and `0b00000111` are reserved for special form of public keys for historical compatibility with bitcoin code.
For other object:
 * Lowest bit always encodes whether y-coordinate of point is odd or even.
 * `0b0000001x` header is used for public keys
 * `0b0000101x` header is used for generators
 * `0b0000100x` header is used for pedersen commitments

Since point object is a uniting type, and there will probably be other specific objects which represent points in the future, it is pertinent to use a distinctive header, such as `0b1000000x` or `0b1111111x`.

**Comment by WTRMQDev** [comment]
Points module #33 which implements general point interface and uses header `0b1000000x` for points serialization.

**Comment by apoelstra** [comment]
Thanks for your work but we don't want to go this direction. In our rangeproofs we don't think in terms of "odd" or "even" points and in schnorr signatures our R-coordinates are 32 bytes rather than 33. I don't see how a general API could handle this while still providing any useful generalization.
