### ISSUE TITLE
Document max length of message array in rangeproof_sign()

### ISSUE THREAD

**Issue by real-or-random** [ElementsProject/secp256k1-zkp#42]
https://github.com/ElementsProject/secp256k1-zkp/blob/43dd1f4fe732268734f0b4efd8e99ea4ff1e49a1/include/secp256k1_rangeproof.h#L240
In particular, size values > 4096 are undefined behavior but also shorter array won't work properly.

**Comment by instagibbs** [comment]
>shorter array won't work properly.

Long ago memory recalls this as well.

**Comment by instagibbs** [comment]
Whatever I mean by this, I was probably wrong. https://github.com/ElementsProject/elements/pull/673

**Comment by instagibbs** [comment]
It appears to me that values < 4096 are fine as long as `msg_len` is at or under that value.

**Comment by real-or-random** [comment]
Right... I don't know what made me think that this is a problem.

Well, I mean, the length is not documented but you can't get UB if you pass the right `msg_len`... And the actual formula is `128 * rings` where rings depends on a lot of stuff, so I understand now why this has not been documented:
https://github.com/ElementsProject/secp256k1-zkp/blob/43dd1f4fe732268734f0b4efd8e99ea4ff1e49a1/src/modules/rangeproof/rangeproof_impl.h#L169

I guess it's good enough to document that
 * `msg_len == 4096` is always enough
 *  if the call succeeds with a certain `value` and `value` is a b-bit number, then any call with the same proof parameters and a b-bit `value`  will also succeed
