### ISSUE TITLE
Question about whitelist module and W = -Q

### ISSUE THREAD

**Issue by dgpv** [ElementsProject/secp256k1-zkp#52]
I looked at at src/modules/whitelist/whitelist.md and at secp256k1_whitelist_compute_keys_and_message(), to better understand how whitelisting is done. 
https://github.com/ElementsProject/secp256k1-zkp/blob/1bbad3a04be42edb1dda16c9eab24345b1f63c5d/src/modules/whitelist/whitelist_impl.h#L120

I noticed that the case when `H + Q` addition results in infinity is not treated as an error. This might be by design, but it seems to me that this might result in a potential problem. My understanding may be wrong or incomplete, and this might be a non-issue, but I would like to know what am I missing. Does the following looks correct ?

If an attacker knows the online key P, he can whitelist garbage keys, but he can also whtielist `-Q`.

 The formula: `L_j = P_j + H(W + Q_j)(W + Q_j)`. If `W = -Q`, the sum `W + Q` will be infinity.

If the sum is infinity, secp256k1_whitelist_tweak_pubkey() will not do anything, and only online key will be stored in keys[i]  (if `a` is infinity, `secp256k1_gej_add_ge_var(&r, &a, &b, NULL)` sets `r = b`).

Attacker will sign with just online key to whitelist sending funds to `-Q`, but the fact that the funds are still accessible with `-Q` will not be obvious, and if the participant does not know about this possibility, this could result in eventual leak of `Q`: participant might think that funds were sent to garbage address, the funds controlled by `Q` would be preceived as 'lost', and the security measures for `Q` might be lessened.

Of course if participant knows and checks for this, there would be no problem. But wouldn't it be better to return 0 from secp256k1_whitelist_compute_keys_and_message() if the result of `W+Q` is infinity ? Or maybe just document this possibility so participants will know to check for it.

**Comment by jonasnick** [comment]
> If an attacker knows the online key P, he can whitelist garbage keys, but he can also whtielist -Q.

`-Q` is a garbage key. I don't see how `-Q` would be worse than any other garbage key.

**Comment by apoelstra** [comment]
Agreed, we should check for infinity and return 0, so that we don't have to think about this case :). But I also agree that in practice it seems fine.

**Comment by dgpv** [comment]
> -Q is a garbage key. I don't see how -Q would be worse than any other garbage key.

It is better than garbage key, because the funds can actually be recovered by the owner of Q. But it is not immediately obvious, and in the described hypothetical situation the owner of Q can miss that.

**Comment by jonasnick** [comment]
It's not better than a garbage key because the garbage key `W = E - Q` can be recovered just as well if the attacker sends the DLog of `E` to the owner of `Q`.

The attacker could for example choose `E = 1*G` which seems easy to brute force but `Q` can miss.

**Comment by dgpv** [comment]
I see, thanks for explanation

**Comment by dgpv** [comment]
So an attacker can expend resources to brute force some `E` that would not be so easy to brute force as `1*G`, but still possible, and then hold the funds hostage by offering to release `E` to the owner of `Q` for ransom (because the time for the owner of `Q` can be much more valuable, and spending it bruteforcing might be more expensive than paying ransom - for example, getting funds back quickly might mean the theft would not be made public)

//I guess discussing this hypothetical scenarios may be out of place here, so please close the issue if you think this is irrelevant.
