### ISSUE TITLE
One silly question about build setting

### ISSUE THREAD

**Issue by spartucus** [ElementsProject/secp256k1-zkp#78]
I'm using the library to implement my own module.

However when I use `&ctx->ecmult_gen_ctx` in my `main_impl.h`, the compiler complains with `Incomplete definition of type 'struct secp256k1_context_struct'`.

I notice the `secp256k1_context_struct` struct was defined in `secp256k1.c` file, so all struct member should be invisible to other files, but I notice other `main_impl.h` file, they also just include `secp256k1.h` not `.c` file, and they just work fine. Why it build succeed? 

What's the magic here?

**Comment by jonasnick** [comment]
`secp256k1_context_struct` is an opaque struct and its members are not meant to be accessed outside of libsecp (think "private" in object oriented languages). What are you trying to do?

**Comment by spartucus** [comment]
Thanks for reply. Yes, I know it's a opaque struct, but how could it fine in `src/modules/schnorrsig/main_impl.h`? https://github.com/ElementsProject/secp256k1-zkp/blob/secp256k1-zkp/src/modules/schnorrsig/main_impl.h#L61

I'm doing same thing like these modules, a different crypto algorithm using secp256k1.

**Comment by spartucus** [comment]
Same thing like `secp256k1_pubkey_load`, it's a static function defined in `secp256k1.c`, and it's used in many other file like `src/modules/schnorrsig/main_impl.h#114`. I'm totally confused here.

**Comment by spartucus** [comment]
Found answer:). All these `main_impl.h` was included in secp256k1.c.
