### ISSUE TITLE
MuSig build issues

### ISSUE THREAD

**Issue by jharveyb** [ElementsProject/secp256k1-zkp#81]
As of now secp256k1-zkp builds successfully when the MuSig module is enabled, though when trying to use it there are two problems:

1 - the module is missing the extern header/footer, so it must be externed manually - not sure if this is intentional since the module is experimental, but other experimental modules like schnorrsig do include this.

2 - On line 272, the last ARG_NONNULL flag does not match the function definition (args 1-3 must be non-null, not 1-2 & 4). This results in this error when building a project that includes secp256k1-zkp built with the musig module:

secp256k1-zkp/.libs/include/secp256k1.h:153:70: error: nonnull argument references non-pointer operand (argument 1, operand 4)
 define SECP256K1_ARG_NONNULL(_x)  __attribute__ ((__nonnull__(_x)))
                                                                      ^
secp256k1-zkp/.libs/include/secp256k1_musig.h:272:53: note: in expansion of macro ‘SECP256K1_ARG_NONNULL’
 ) SECP256K1_ARG_NONNULL(1) SECP256K1_ARG_NONNULL(2) SECP256K1_ARG_NONNULL(4);
                                                     ^~~~~~~~~~~~~~~~~~~~~

I've fixed this by just changing the 4 to a 3 on that line.

**Comment by jonasnick** [comment]
Thanks. Opened PR #82 to fix this.
