### ISSUE TITLE
rebase on bitcoin-core/secp256k1

### ISSUE THREAD

**Issue by benma** [ElementsProject/secp256k1-zkp#85]
Hi

I would have done a PR, but I was not sure how you handle rebasing. 

Anyway, it would be great to rebase this on upstream. I am particularly interested in pulling in this change: https://github.com/bitcoin-core/secp256k1/pull/337, so I can skip some custom commits on my fork of libwally-core.

**Comment by real-or-random** [comment]
The last rebase has been 6 months  ago, so yes we can do this if it's helpful for you. I can't promise you a date though.

We typically we go with at least two people in parallel through the process and check that we arrive at the same code at a few checkpoints on the way. So yes, no need to open a PR, we'll handle it.

**Comment by benma** [comment]
Ah, didn't realize it was so involved. In this case, thanks! No need to rush, I can continue with manual patching for a while.

**Comment by apoelstra** [comment]
We should also warn the Trezor people and find a minimally disruptive way to do things, this time. (Maybe it is sufficient to just rename the old branch and then they need to change nothing? I don't know.)

**Comment by real-or-random** [comment]
I think we settled on renaming the old branch to `secp256k1-zkp-YYYY-MM-DD`, see your comment here: https://github.com/ElementsProject/secp256k1-zkp/issues/68#issuecomment-498351737

**Comment by benma** [comment]
Hello again. Are there any plans to rebase? There have been a bunch of interesting but also invasive PRs which makes it harder to rebase custom patches on both secp256k1 repos (upstream and this one):

https://github.com/bitcoin-core/secp256k1/pull/708
https://github.com/bitcoin-core/secp256k1/pull/709
https://github.com/bitcoin-core/secp256k1/pull/710

Would be great to update this repo again. I am guessing that more frequent rebasing is also less effort overall.

Happy to help if I can be of assistance, let me know.

**Comment by real-or-random** [comment]
Good points, we should think about this now. On the other hand, there will hopefully be a secp256k1 release soon, so maybe it's better to wait? No idea at the moment, we should discuss this. 

Independently of this, I suggested a while ago to move some code here around. The goal is not to touch any upstream in our fork here (except maybe build system files). This is realistic because we only add features to upstream but don't change then. This will make rebasing a little bit easier.

**Comment by benma** [comment]
>  On the other hand, there will hopefully be a secp256k1 release soon

What do you mean? The secp256k1 repo doesn't have releases nor tags.

> Independently of this, I suggested a while ago to move some code here around.

Sounds good. Whatever is fastest :)

**Comment by jonasnick** [comment]
Fixed by #91
