### ISSUE TITLE
combinePubKeys should not allow for n_pubkeys==1

### ISSUE THREAD

**Issue by ysangkok** [ElementsProject/secp256k1-zkp#89]
There is this line in combine_pubkeys:

`ARG_CHECK(n_pubkeys > 0);`

Given that it doesn't make sense for n_pubkeys to be 1, I was wondering if this check should be changed to be "> 1"?

**Comment by gmaxwell** [comment]
why wouldn't it?  n_pubkeys = 1 is well defined and has an obvious sensible behaviour. If the interface forces more than one then a caller needs to handle an additional corner case that would otherwise just work.

**Comment by real-or-random** [comment]
Hm. You can also combine the same pubkey n times with itself. I don't have a use case for this either but it's not broken or wrong in any sense, so I tend not to put restrictions here. But you're right, it's somehow confusing. I'm indifferent.

**Comment by ysangkok** [comment]
Ok, if the current behavior is to be kept, it would be nice to document it. How about a footnote in `musig.md` that says that the API supports a single signer? The footnote could be referenced each time a plural like "participants" or "public keys" is used.

**Comment by apoelstra** [comment]
I'd rather not complicate the exposition for the sake of this usecase. The current text makes sense for n=1 (aside from being ungrammatical) and it never occurred to me that n=1 might not work. Though perhaps I am just too close to this.

**Comment by sipa** [comment]
I don't understand what's the issue here. Does the function not do exactly what you'd expect with 1 input?
